import Foundation

/// A file the generator writes, with its path relative to the package root.
package struct GeneratedFile: Hashable, Sendable {
  /// The full text of the file.
  package let contents: String
  /// The path relative to the package root.
  package let path: String

  package init(contents: String, path: String) {
    self.contents = contents
    self.path = path
  }
}

/// Renders a catalog as the Swift files and resources checked into `Sources/SwiftSymbols`.
///
/// Output depends only on the catalog and the build string, so regenerating from the same data
/// produces byte-identical files and a clean diff. The Swift output is already in swift-format's
/// style, because the repository gate compares it byte for byte with the checked-in files.
package struct Emitter: Sendable {
  /// The first words of every generated Swift file, which the repository gate looks for.
  package static let headerPrefix = "// Generated by swift-symbols-generate"
  /// The first words of every generated resource, which the repository gate looks for.
  package static let resourceHeaderPrefix = "# Generated by swift-symbols-generate"

  /// The widest doc-comment text, so `  /// ` plus the text stays within swift-format's
  /// 100-column limit.
  private static let docWidth = 94
  private static let generatedDirectory = "Sources/SwiftSymbols/Generated/"
  private static let lineLimit = 100
  private static let resourcesDirectory = "Sources/SwiftSymbols/Resources/"

  /// The macOS build the data came from.
  package let build: String
  /// The catalog to render.
  package let catalog: SymbolCatalog

  package init(build: String, catalog: SymbolCatalog) {
    self.build = build
    self.catalog = catalog
  }

  /// The header every Swift file starts with, ending in a blank line.
  package var header: String {
    """
    \(Self.headerPrefix) from SF Symbols \(catalog.sfSymbolsYear), macOS build \(build). Do not edit.
    // Regenerate with `bash Scripts/generate-catalog.sh` after an Xcode or macOS update.

    """
  }

  /// Every file, symbols first, in a stable order.
  package func files() -> [GeneratedFile] {
    var files: [GeneratedFile] = []
    var groups: [String: [SymbolEntry]] = [:]
    for entry in catalog.entries {
      groups[Self.groupKey(for: entry.identifier), default: []].append(entry)
    }
    for key in groups.keys.sorted() {
      files.append(
        GeneratedFile(
          contents: symbolsFile(groups[key] ?? []),
          path: "\(Self.generatedDirectory)SFSymbol+Symbols-\(key).swift"))
    }
    files.append(
      GeneratedFile(
        contents: aliasesFile(), path: "\(Self.generatedDirectory)SFSymbol+Aliases.swift"))
    files.append(
      GeneratedFile(
        contents: categoriesFile(), path: "\(Self.generatedDirectory)SFSymbol.Category+All.swift")
    )
    files.append(
      GeneratedFile(contents: versionFile(), path: "\(Self.generatedDirectory)CatalogVersion.swift")
    )
    files.append(
      GeneratedFile(contents: symbolsResource(), path: "\(Self.resourcesDirectory)symbols.tsv"))
    files.append(
      GeneratedFile(contents: aliasesResource(), path: "\(Self.resourcesDirectory)aliases.tsv"))
    files.append(
      GeneratedFile(
        contents: categoriesResource(), path: "\(Self.resourcesDirectory)categories.tsv"))
    return files
  }

  /// Splits `text` on spaces into lines no longer than `width`, never breaking inside a word.
  package static func wrap(_ text: String, width: Int = docWidth) -> [String] {
    var lines: [String] = []
    var current = ""
    for word in text.split(separator: " ") {
      if current.isEmpty {
        current = String(word)
      } else if current.count + 1 + word.count > width {
        lines.append(current)
        current = String(word)
      } else {
        current += " " + word
      }
    }
    if !current.isEmpty { lines.append(current) }
    return lines
  }

  /// `@available(*, deprecated, renamed: "identifier")`, broken as swift-format breaks it.
  private static func deprecation(renamed identifier: String) -> String {
    let renamed = "renamed: \"\(identifier)\""
    return firstFitting([
      ["  @available(*, deprecated, \(renamed))"],
      ["  @available(", "    *, deprecated, \(renamed)", "  )"],
      ["  @available(", "    *, deprecated,", "    \(renamed)", "  )"],
    ])
  }

  /// Doc-comment lines for `text`, wrapped so the whole line stays under swift-format's limit.
  private static func docLines(_ text: String) -> String {
    wrap(field(text)).map { "  /// \($0)\n" }.joined()
  }

  /// A field with tabs and newlines replaced, so a row stays one line of one record.
  private static func field(_ value: String) -> String {
    value.replacingOccurrences(of: "\t", with: " ").replacingOccurrences(of: "\n", with: " ")
  }

  /// The first layout whose lines all fit swift-format's limit, or the last, most broken one.
  ///
  /// The candidates are swift-format's own line breaks, tried in the order its pretty printer
  /// tries them, so a long name produces exactly the text the formatter would.
  private static func firstFitting(_ layouts: [[String]]) -> String {
    let fitting = layouts.first { $0.allSatisfy { $0.count <= lineLimit } }
    return (fitting ?? layouts.last ?? []).map { $0 + "\n" }.joined()
  }

  /// The file a declaration lands in: its first letter, or `digits` for a leading digit.
  private static func groupKey(for identifier: String) -> String {
    let bare = identifier.replacingOccurrences(of: "`", with: "")
    guard let first = bare.first, first.isLetter else { return "digits" }
    return String(first).lowercased()
  }

  /// A list item with commas removed too, so the list splits back into the same items.
  private static func listItem(_ value: String) -> String {
    field(value).replacingOccurrences(of: ",", with: "")
  }

  /// The opening of `public static var identifier: type {`, broken as swift-format breaks it.
  private static func staticVar(_ identifier: String, type: String) -> String {
    firstFitting([
      ["  public static var \(identifier): \(type) {"],
      ["  public static var \(identifier): \(type)", "  {"],
      ["  public static var \(identifier):", "    \(type)", "  {"],
      ["  public static", "    var \(identifier): \(type)", "  {"],
      ["  public static", "    var \(identifier):", "    \(type)", "  {"],
    ])
  }

  /// A getter body of `SFSymbol(unchecked: "name")`, broken as swift-format breaks it.
  private static func uncheckedInitializer(_ name: String) -> String {
    let literal = "\"\(name)\""
    return firstFitting([
      ["    SFSymbol(unchecked: \(literal))"],
      ["    SFSymbol(", "      unchecked: \(literal))"],
      ["    SFSymbol(", "      unchecked: \(literal)", "    )"],
      ["    SFSymbol(", "      unchecked:", "        \(literal))"],
      ["    SFSymbol(", "      unchecked:", "        \(literal)", "    )"],
    ])
  }

  private func aliasesFile() -> String {
    var out = header + "\nextension SFSymbol {\n"
    let attributes = Dictionary(
      uniqueKeysWithValues: catalog.entries.map { ($0.name, $0.availabilityAttribute) })
    for alias in catalog.aliases {
      out += Self.docLines("`\(alias.name)`, renamed to ``\(alias.targetIdentifier)``.")
      if let attribute = attributes[alias.target] ?? nil { out += "  \(attribute)\n" }
      out += Self.deprecation(renamed: alias.targetIdentifier)
      out += Self.staticVar(alias.identifier, type: "SFSymbol")
      out += "    .\(alias.targetIdentifier)\n  }\n"
    }
    return out + "}\n"
  }

  private func categoriesFile() -> String {
    var out = header + "\nextension SFSymbol.Category {\n"
    for category in catalog.categories {
      out += Self.docLines(
        "The `\(category.key)` category. Apple's icon for it is `\(category.icon)`.")
      out += Self.staticVar(
        SwiftIdentifier.declaration(for: category.key), type: "SFSymbol.Category")
      out += "    SFSymbol.Category(key: \"\(category.key)\")\n  }\n"
    }
    return out + "}\n"
  }

  private func symbolsFile(_ entries: [SymbolEntry]) -> String {
    var out = header + "\nextension SFSymbol {\n"
    for entry in entries {
      out += "  /// `\(entry.name)`\n  ///\n"
      var facts: [String] = []
      if !entry.categories.isEmpty {
        facts.append("Categories: \(entry.categories.joined(separator: ", ")).")
      }
      if !entry.searchTerms.isEmpty {
        facts.append("Search terms: \(entry.searchTerms.joined(separator: ", ")).")
      }
      if !facts.isEmpty {
        out += Self.docLines(facts.joined(separator: " ")) + "  ///\n"
      }
      let since = SymbolCatalog.platforms.map { "\($0) \(entry.release[$0] ?? "")" }
      out += Self.docLines("Available since \(since.joined(separator: ", ")).")
      if let restriction = entry.restriction {
        out += "  ///\n" + Self.docLines("Restriction: \(restriction)")
      }
      if let attribute = entry.availabilityAttribute { out += "  \(attribute)\n" }
      out += Self.staticVar(entry.identifier, type: "SFSymbol")
      out += Self.uncheckedInitializer(entry.name) + "  }\n"
    }
    return out + "}\n"
  }

  private func versionFile() -> String {
    header + """

      extension SFSymbol {
        /// The SF Symbols release and macOS build the catalog was generated from.
        public static var catalogVersion: CatalogVersion {
          CatalogVersion(macOSBuild: "\(build)", sfSymbolsYear: \(catalog.sfSymbolsYear))
        }
      }

      """
  }

  private var resourceHeader: String {
    "\(Self.resourceHeaderPrefix) from SF Symbols \(catalog.sfSymbolsYear), "
      + "macOS build \(build). Do not edit.\n"
  }

  private func aliasesResource() -> String {
    resourceHeader + catalog.aliases.map { "\($0.name)\t\($0.target)\n" }.joined()
  }

  private func categoriesResource() -> String {
    resourceHeader + catalog.categories.map { "\($0.key)\t\($0.icon)\n" }.joined()
  }

  private func symbolsResource() -> String {
    var out = resourceHeader
    for entry in catalog.entries {
      var fields = [entry.name, entry.year]
      fields += SymbolCatalog.platforms.map { entry.release[$0] ?? "" }
      fields += [
        entry.categories.map(Self.listItem).joined(separator: ","),
        entry.searchTerms.map(Self.listItem).joined(separator: ","),
        Self.field(entry.restriction ?? ""),
        entry.filledName ?? "",
        entry.base,
        entry.variants.joined(separator: ","),
      ]
      out += fields.joined(separator: "\t") + "\n"
    }
    return out
  }
}
